name: ci

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: 12
      - run: yarn install --ignore-scripts
      - run: yarn run ci:prettier-check
      - run: yarn run lint

  test:
    needs: [lint]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        node-version: [12]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --ignore-scripts
      - run: yarn run ci:test

  prepack:
    name: prepack
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Install dependencies
      run: npm install

    - name: Update README
      run: yarn prepack

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        message: "Update Plugin Documentation"
        add: "README.md"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}