name: publish-stable:npm

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: 12
            registry-url: https://registry.npmjs.org/
      - run: yarn install --ignore-scripts
      - run: yarn build
      - run: npm publish --access=public
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
            IS_CI: "true"
  
  prepack:
    name: prepack
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm install
    - name: Update README
      run: yarn prepack
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        message: "[Automatic] Toolbelt plugin documentation"
        add: "README.md"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}